# Generated by Django 4.2.11 on 2024-10-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('belongs_to_collection', models.BooleanField()),
                ('budget', models.IntegerField()),
                ('homepage', models.CharField(max_length=200)),
                ('imdb_id', models.CharField(max_length=20)),
                ('original_title', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=2000)),
                ('popularity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=5)),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('genre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(null=True, unique=True)),
                ('keyword', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, null=True, unique=True)),
                ('language', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('gender', models.IntegerField()),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('known_for_department', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('profile_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='LT_Films_Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.film')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.language')),
            ],
        ),
        migrations.CreateModel(
            name='LT_Films_Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.film')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.keyword')),
            ],
            options={
                'unique_together': {('film', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='LT_Films_Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.genre')),
            ],
            options={
                'unique_together': {('film', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='LT_Films_Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.person')),
            ],
            options={
                'unique_together': {('film', 'person')},
            },
        ),
        migrations.CreateModel(
            name='LT_Films_Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.country')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.film')),
            ],
            options={
                'unique_together': {('film', 'country')},
            },
        ),
        migrations.CreateModel(
            name='LT_Films_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.company')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.film')),
            ],
            options={
                'unique_together': {('film', 'company')},
            },
        ),
        migrations.CreateModel(
            name='LT_Films_Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_id', models.IntegerField()),
                ('character', models.CharField(max_length=200)),
                ('credit_id', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mountainLionMovies.person')),
            ],
            options={
                'unique_together': {('film', 'person')},
            },
        ),
    ]
